import { TodoProps } from "@/types";
import { update } from "lodash";

export const summary = {
    "in_progress": 10,
    "completed": 100,
    "projects": [
        {
            "name": "+documentation",
            "tags": ["work", "home"],
            "in_progress": 5,
            "completed": 30,
            "start": "2024-01-01",
            "end": "2024-12-31"
        },
        {
            "name": "+codeReview",
            "tags": ["work", "home"],
            "in_progress": 5,
            "completed": 53,
            "start": "2024-01-01",
            "end": "2024-12-31"
        },
        {
            "name": "+testing",
            "tags": [],
            "in_progress": 3,
            "completed": 24,
            "start": "2024-02-01",
            "end": "2024-12-31"
        },
        {
            "name": "+deployment new tesat project　あｓｄふぁｓｄｆ　：ｗ ",
            "tags": ["work", "production", "home", "office", "testing"],
            "in_progress": 1002,
            "completed": 3000,
            "start": "2024-03-01",
            "end": "2024-12-31"
        }
    ]
}

export const activityYear = ['2024']
export const activityDate = [
    {
        date: '2024-01-01',
        count: 0,
        level: 0,
    },
    {
        date: '2024-06-22',
        count: 2,
        level: 1,
    },
    {
        date: '2024-06-23',
        count: 2,
        level: 2,
    },
    {
        date: '2024-06-24',
        count: 2,
        level: 3,
    },
    {
        date: '2024-06-25',
        count: 16,
        level: 4,
    },
    {
        date: '2024-11-29',
        count: 11,
        level: 3,
    },
];


export const timeline_page1 = [
    {
        id: '1',
        is_complete: false,
        priority: 'A',
        completionDate: null,
        creationDate: '2024-12-01',
        text: 'Complete the project documentation',
        detail: 'Finish writing the documentation for the new project',
        project: '+documentation',
        context: '@work',
        isArchived: false,
        sort: 1,
        limitDate: '2024-01-10',
        indent: 0,
        updateDate: '2024-12-22T16:23:09.000Z',
    },
    {
        id: '2',
        is_complete: true,
        priority: 'B',
        completionDate: '2024-11-22',
        creationDate: '2024-06-20',
        text: 'Review pull requests',
        detail: 'Review the pending pull requests in the repository',
        project: '+codeReview',
        context: '@home',
        isArchived: false,
        sort: 2,
        limitDate: '2024-06-21',
        indent: 0,
        updateDate: '2024-12-11T16:23:09.000Z',
    },
    {
        id: '3',
        is_complete: false,
        priority: 'C',
        completionDate: null,
        creationDate: '2024-06-23',
        text: 'Plan the next sprint',
        detail: 'Organize and plan tasks for the next sprint',
        project: '+sprintPlanning',
        context: '@office',
        isArchived: false,
        sort: 3,
        limitDate: '2024-06-30',
        indent: 0,
        updateDate: '2024-12-11T16:23:09.000Z',
    },
    {
        id: '4',
        is_complete: false,
        priority: 'D',
        completionDate: null,
        creationDate: '2024-07-01',
        text: 'Update project roadmap',
        detail: 'Revise and update the project roadmap for Q3',
        project: '+roadmap',
        context: '@work',
        isArchived: false,
        sort: 4,
        limitDate: '2024-07-05',
        indent: 0,
        updateDate: '2024-12-01T16:23:09.000Z',
    },
    {
        id: '5',
        is_complete: true,
        priority: 'E',
        completionDate: '2024-07-10',
        creationDate: '2024-07-08',
        text: 'Fix critical bugs',
        detail: 'Address and fix critical bugs reported by users',
        project: '+bugfix',
        context: '@home',
        isArchived: false,
        sort: 5,
        limitDate: '2024-07-09',
        indent: 0,
        updateDate: '2024-12-01T16:23:09.000Z',
    },
    {
        id: '6',
        is_complete: false,
        priority: 'F',
        completionDate: null,
        creationDate: '2024-07-15',
        text: 'Conduct user interviews',
        detail: 'Interview users to gather feedback on the new features',
        project: '+userResearch',
        context: '@office',
        isArchived: false,
        sort: 6,
        limitDate: '2024-07-20',
        indent: 0,
        updateDate: '2024-11-21T16:23:09.000Z',
    },
    {
        id: '7',
        is_complete: false,
        priority: 'G',
        completionDate: null,
        creationDate: '2024-07-20',
        text: 'Prepare for product launch',
        detail: 'Finalize preparations for the upcoming product launch',
        project: '+launch',
        context: '@work',
        isArchived: false,
        sort: 7,
        limitDate: '2024-07-25',
        indent: 0,
        updateDate: '2024-11-21T16:23:09.000Z',
    },
    {
        id: '8',
        is_complete: true,
        priority: 'H',
        completionDate: '2024-07-30',
        creationDate: '2024-07-28',
        text: 'Write blog post',
        detail: 'Write and publish a blog post about the new release',
        project: '+blog',
        context: '@home',
        isArchived: false,
        sort: 8,
        limitDate: '2024-07-29',
        indent: 0,
        updateDate: '2024-11-21T16:23:09.000Z',
    },
    {
        id: '9',
        is_complete: false,
        priority: 'I',
        completionDate: null,
        creationDate: '2024-08-01',
        text: 'Design new feature',
        detail: 'Create design mockups for the new feature',
        project: '+design',
        context: '@office',
        isArchived: false,
        sort: 9,
        limitDate: '2024-08-05',
        indent: 0,
        updateDate: '2024-11-20T16:23:09.000Z',
    },
    {
        id: '10',
        is_complete: false,
        priority: 'J',
        completionDate: null,
        creationDate: '2024-08-10',
        text: 'Optimize performance',
        detail: 'Improve the performance of the application',
        project: '+performance',
        context: '@work',
        isArchived: false,
        sort: 10,
        limitDate: '2024-08-15',
        indent: 0,
        updateDate: '2024-11-20T16:23:09.000Z',
    }
];

export const timeline_page2 = [
    {
        id: '11',
        is_complete: false,
        priority: 'K',
        completionDate: null,
        creationDate: '2024-08-20',
        text: 'Conduct code review',
        detail: 'Review the code for the new feature implementation',
        project: '+codeReview',
        context: '@work',
        isArchived: false,
        sort: 11,
        limitDate: '2024-08-25',
        indent: 0,
        updateDate: '2024-10-21T16:23:09.000Z',
    },
    {
        id: '12',
        is_complete: true,
        priority: 'L',
        completionDate: '2024-08-30',
        creationDate: '2024-08-28',
        text: 'Deploy new version',
        detail: 'Deploy the new version of the application to production',
        project: '+deployment',
        context: '@office',
        isArchived: false,
        sort: 12,
        limitDate: '2024-08-29',
        indent: 0,
        updateDate: '2024-10-20T16:23:09.000Z',
    },
    {
        id: '13',
        is_complete: false,
        priority: 'M',
        completionDate: null,
        creationDate: '2024-09-01',
        text: 'Write unit tests',
        detail: 'Write unit tests for the new feature',
        project: '+testing',
        context: '@home',
        isArchived: false,
        sort: 13,
        limitDate: '2024-09-05',
        indent: 0,
        updateDate: '2024-10-11T16:23:09.000Z',
    },
    {
        id: '14',
        is_complete: false,
        priority: 'N',
        completionDate: null,
        creationDate: '2024-09-10',
        text: 'Update documentation',
        detail: 'Update the project documentation with the latest changes',
        project: '+documentation',
        context: '@work',
        isArchived: false,
        sort: 14,
        limitDate: '2024-09-15',
        indent: 0,
        updateDate: '2024-10-11T16:23:09.000Z',
    },
    {
        id: '15',
        is_complete: true,
        priority: 'O',
        completionDate: '2024-09-20',
        creationDate: '2024-09-18',
        text: 'Fix minor bugs',
        detail: 'Fix minor bugs reported by users',
        project: '+bugfix',
        context: '@office',
        isArchived: false,
        sort: 15,
        limitDate: '2024-09-19',
        indent: 0,
        updateDate: '2024-10-11T16:23:09.000Z',
    }
]
